apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: my-nodejs-pipeline
spec:
  resources:
    - name: my-nodejs-git
      type: git
    - name: my-nodejs-image-dev
      type: image
    - name: my-nodejs-image-stage
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'my-nodejs'
    - name: PATH_CONTEXT
      value: './'
    - name: APP_VERSION
      description: The version of the application
      default: '1.0'      
    - name: AUTHORS_API_KEY
      description: The OCP secret that contains DB credentials
      default: 'authors-secret-api'
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: 'env-dev'
    - name: PROMOTE_PROJECT
      description: The project where you deploy the app
      default: 'env-stage'

  tasks:
  - name: build
    taskRef:
      name: s2i-nodejs
    resources:       
      inputs:
        - name: source
          resource: my-nodejs-git
      outputs:
        - name: image
          resource: my-nodejs-image-dev

  - name: deploy
    taskRef:
      name: deploy-nodejs-app
    runAfter:
      - build
    params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"  
        - name: AUTHORS_API_KEY
          value: "$(params.AUTHORS_API_KEY)"
        - name: DEPLOY_PROJECT
          value: "$(params.DEPLOY_PROJECT)"    
    resources:
      inputs:
        - name: image
          resource: my-nodejs-image-dev

  - name: test
    taskRef:
      name: test-nodejs-app
    runAfter:
      - deploy
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"

  - name: promote
    taskRef:
      name: promote-nodejs-app
    runAfter:
      - test
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: AUTHORS_API_KEY
        value: "$(params.AUTHORS_API_KEY)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"
      - name: PROMOTE_PROJECT
        value: "$(params.PROMOTE_PROJECT)"
    resources:
      inputs:
        - name: image
          resource: my-nodejs-image-dev
      outputs:
        - name: image
          resource: my-nodejs-image-stage